### ISSUE TITLE
Add repo defaults

### ISSUE THREAD

**Issue by rahearn** [GSA-TTS/compliance-trestle-gsa#4]
```[tasklist]
### Tasks
- [x] Add issue and PR templates
- [x] Add actions to run linting and tests on PRs
- [x] Update branch protections to require linting and tests
```
